name: Build & Test

on:
  push:
    branches: [ main, beta, release ]
  pull_request:
    branches: [ main, beta, release ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore AeroDebrief.sln

      - name: Build
        run: dotnet build AeroDebrief.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test AeroDebrief.sln --configuration Release --no-build --verbosity normal

      - name: Upload CLI artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AeroDebrief-CLI-${{ github.ref_name }}
          path: src/AeroDebrief.CLI/bin/Release/net9.0/

      - name: Upload UI artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AeroDebrief-UI-${{ github.ref_name }}
          path: src/AeroDebrief.UI/bin/Release/net9.0-windows/
